apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Lumumba95/docker-development-youtube-series.git
    targetRevision: HEAD
    path: argo
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: example-app

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
      